# Generated by Django 6.0 on 2025-12-19 09:52

import apps.sales.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('receipt_number', models.CharField(default=apps.sales.models.generate_receipt_number, max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('is_receipt_issued', models.BooleanField(default=False)),
                ('receipt_issued_date', models.DateTimeField(blank=True, null=True)),
                ('sale_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Receipt',
                'verbose_name_plural': 'Sales Receipts',
                'db_table': 'sales_receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salesreceipt')),
            ],
            options={
                'verbose_name': 'Receipt Payment',
                'verbose_name_plural': 'Receipt Payments',
                'db_table': 'receipt_payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('WEBSITE', 'Website'), ('LOGO', 'Logo'), ('SOCIAL_MEDIA', 'Social Media Accounts'), ('MARKETING_MATERIAL', 'Marketing Material'), ('OTHER', 'Other Custom Services')], max_length=50)),
                ('service_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_items', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='sales.salesreceipt')),
            ],
            options={
                'verbose_name': 'Delivery Service Item',
                'verbose_name_plural': 'Delivery Service Items',
                'db_table': 'delivery_service_items',
                'ordering': ['created_at'],
            },
        ),
    ]
