# Generated by Django 6.0 on 2025-12-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_phone_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LEAD_DISTRIBUTER', 'LEAD_DISTRIBUTER'), ('FRANCHISE_CALLER', 'Franchise Caller'), ('PACKAGE_CALLER', 'Package Caller'), ('TEAM_LEADER', 'Team Leader'), ('SUPER_ADMIN', 'Super Admin')], default='FRANCHISE_CALLER', max_length=20),
        ),
    ]
