# Generated by Django 6.0 on 2026-01-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_present',
            field=models.BooleanField(default=True, help_text='If false, caller will not receive leads in auto distribution'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_present', 'is_active'], name='users_role_3e87a9_idx'),
        ),
    ]
