# Generated by Django 6.0 on 2026-01-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_present_user_users_role_3e87a9_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LEAD_DISTRIBUTER', 'LEAD_DISTRIBUTER'), ('FRANCHISE_CALLER', 'Franchise Caller'), ('PACKAGE_CALLER', 'Package Caller'), ('TEAM_LEADER', 'Team Leader'), ('SUPER_ADMIN', 'Super Admin'), ('PROBLEM_SOLVER', 'Problem solver')], default='FRANCHISE_CALLER', max_length=20),
        ),
    ]
