# Generated by Django 6.0 on 2026-01-16 09:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('problem_type', models.CharField(choices=[('BOOKING', 'Booking Issue'), ('PAYMENT', 'Payment/Pricing Issue'), ('CANCELLATION', 'Cancellation/Refund Issue'), ('ITINERARY', 'Itinerary/Planning Issue'), ('ACCOMMODATION', 'Accommodation/Hotel Issue'), ('TRANSPORT', 'Transport/Vehicle Issue'), ('GUIDE', 'Guide/Staff Issue'), ('VISA', 'Visa/Documentation Issue'), ('FOOD_CATERING', 'Food/Catering Issue'), ('HEALTH_SAFETY', 'Health/Safety Concern'), ('COMMUNICATION', 'Communication Issue'), ('CUSTOMER_SERVICE', 'Customer Service Issue'), ('WEATHER', 'Weather Related Issue'), ('OTHER', 'Other Issue')], default='OTHER', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('tour_package', models.CharField(blank=True, max_length=200, null=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('reported_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolution_time_minutes', models.IntegerField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('communication_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_problems', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Problem Report',
                'verbose_name_plural': 'Problem Reports',
                'db_table': 'problem_reports',
                'ordering': ['-reported_date'],
                'indexes': [models.Index(fields=['status', 'priority'], name='problem_rep_status_6faf22_idx'), models.Index(fields=['reported_date'], name='problem_rep_reporte_859726_idx'), models.Index(fields=['assigned_to', 'status'], name='problem_rep_assigne_8d4beb_idx'), models.Index(fields=['customer_email'], name='problem_rep_custome_ed9f56_idx'), models.Index(fields=['customer_name'], name='problem_rep_custome_089c19_idx')],
            },
        ),
    ]
