# Generated by Django 6.0 on 2026-01-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemsolver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemreport',
            name='travel_date',
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='tour_package',
            field=models.DateField(blank=True, null=True),
        ),
    ]
