# Generated by Django 6.0 on 2026-01-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemsolver', '0002_remove_problemreport_travel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemreport',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='tour_package',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
