# Generated by Django 6.0 on 2025-12-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('FOLLOW_UP', 'Follow Up'), ('CONVERTED', 'Converted'), ('BUSY', 'Busy'), ('RNR', 'Rnr'), ('CALLBACK', 'Callback'), ('CLOSED', 'Closed'), ('LOST', 'Lost')], default='NEW', max_length=20),
        ),
    ]
