# Generated by Django 6.0 on 2026-01-10 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PulledLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('original_lead_type', models.CharField(choices=[('FRANCHISE', 'Franchise'), ('PACKAGE', 'Package')], max_length=20)),
                ('original_status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('FOLLOW_UP', 'Follow Up'), ('CONVERTED', 'Converted'), ('BUSY', 'Busy'), ('RNR', 'Rnr'), ('CALLBACK', 'Callback'), ('CLOSED', 'Closed'), ('LOST', 'Lost')], max_length=20)),
                ('pull_reason', models.TextField(blank=True, null=True)),
                ('filter_criteria', models.JSONField(blank=True, default=dict, help_text='Stores the filter criteria used for pulling')),
                ('exported', models.BooleanField(default=False)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pulled_versions', to='leads.lead')),
                ('pulled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pulled_leads', to=settings.AUTH_USER_MODEL)),
                ('pulled_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_pulled_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pulled Lead',
                'verbose_name_plural': 'Pulled Leads',
                'db_table': 'pulled_leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='pulled_lead_phone_d18d25_idx'), models.Index(fields=['pulled_by'], name='pulled_lead_pulled__bdd1e6_idx'), models.Index(fields=['pulled_from'], name='pulled_lead_pulled__8492d0_idx'), models.Index(fields=['original_status'], name='pulled_lead_origina_ab85b2_idx'), models.Index(fields=['original_lead_type'], name='pulled_lead_origina_381325_idx'), models.Index(fields=['created_at'], name='pulled_lead_created_df1ac5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('exported', False)), fields=('phone', 'pulled_from'), name='unique_active_pulled_lead')],
            },
        ),
    ]
