# Generated by Django 6.0 on 2026-01-10 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_pulledlead'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pulledlead',
            name='unique_active_pulled_lead',
        ),
    ]
