# Generated by Django 6.0 on 2026-01-10 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_pulledlead_unique_active_pulled_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulledlead',
            name='original_lead',
        ),
        migrations.AddField(
            model_name='pulledlead',
            name='original_lead_id',
            field=models.IntegerField(blank=True, help_text='ID of the original lead before deletion', null=True),
        ),
        migrations.AddIndex(
            model_name='pulledlead',
            index=models.Index(fields=['original_lead_id'], name='pulled_lead_origina_32d54a_idx'),
        ),
    ]
