# Generated by Django 6.0 on 2026-01-12 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_pulledlead_original_lead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PulledLeadTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_pulled_lead_id', models.IntegerField(help_text='Original PulledLead ID')),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('lead_count', models.IntegerField(default=1)),
                ('filters_used', models.JSONField(blank=True, default=dict)),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_transfers', to=settings.AUTH_USER_MODEL)),
                ('transferred_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pulled_lead_transfer_logs',
                'ordering': ['-transferred_at'],
            },
        ),
    ]
